4.
The /home/bob/playbooks/app_install.yaml playbook is responsible for installing a list of 
packages on a remote server(s). The list of packages to be installed is already added to 
the /home/bob/playbooks/inventory file as a list variable called app_list.

Ans:
---
- hosts: all
  become: yes
  tasks:
    - name: Install applications
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ app_list }}"


cd /home/bob/playbooks
ansible-playbook -i inventory app_install.yaml