5.
The /home/bob/playbooks/user_setup.yaml playbook is responsible for setting up a new user 
on a remote server(s). The user details like username, password, and email are already added 
to the /home/bob/playbooks/inventory file as a dictionary variable called user_details.

Ans:
---
- hosts: all
  become: yes
  tasks:
    - name: Set up user
      user:
        name: "{{ user_details.username }}"
        password: "{{ user_details.password }}"
        comment: "{{ user_details.email }}"
        state: present

cd /home/bob/playbooks
ansible-playbook -i inventory user_setup.yaml